package multisolve;

import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Siam
 */
public class workReg extends javax.swing.JFrame {

    /**
     * Creates new form workReg
     */
    Connect conn = new Connect();
    Statement stm;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public workReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        WPass = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        WPhone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton_Photographer = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton_Tutor = new javax.swing.JRadioButton();
        WAge = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton_Female = new javax.swing.JRadioButton();
        jRadioButton_Male = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        WEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        WAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        WLName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        WFName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        submitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/submit.png"))); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton);
        submitButton.setBounds(230, 620, 130, 40);

        WPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(WPass);
        WPass.setBounds(180, 550, 300, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Password");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 550, 90, 22);

        WPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(WPhone);
        WPhone.setBounds(180, 500, 300, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Phone no.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 500, 100, 22);

        buttonGroup2.add(jRadioButton_Photographer);
        jRadioButton_Photographer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton_Photographer.setText("Photographer");
        jRadioButton_Photographer.setToolTipText("");
        jPanel1.add(jRadioButton_Photographer);
        jRadioButton_Photographer.setBounds(290, 450, 160, 31);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Join As");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 450, 90, 29);

        buttonGroup2.add(jRadioButton_Tutor);
        jRadioButton_Tutor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton_Tutor.setText("Tutor");
        jPanel1.add(jRadioButton_Tutor);
        jRadioButton_Tutor.setBounds(180, 450, 77, 31);

        WAge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(WAge);
        WAge.setBounds(180, 400, 100, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Age");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 400, 34, 30);

        buttonGroup1.add(jRadioButton_Female);
        jRadioButton_Female.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton_Female.setText("Female");
        jPanel1.add(jRadioButton_Female);
        jRadioButton_Female.setBounds(310, 350, 107, 30);

        buttonGroup1.add(jRadioButton_Male);
        jRadioButton_Male.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton_Male.setText("Male");
        jPanel1.add(jRadioButton_Male);
        jRadioButton_Male.setBounds(180, 350, 100, 31);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 350, 80, 22);

        WEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(WEmail);
        WEmail.setBounds(180, 290, 380, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Email");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 300, 60, 22);

        WAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(WAddress);
        WAddress.setBounds(180, 230, 380, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Address");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 240, 90, 22);

        WLName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(WLName);
        WLName.setBounds(180, 180, 380, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Last Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 180, 100, 22);

        WFName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(WFName);
        WFName.setBounds(180, 130, 380, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("First Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 140, 100, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Registration as Worker");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 70, 460, 40);

        jPanel2.setBackground(new java.awt.Color(204, 255, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("MultiSolve");

        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 473, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, -10, 740, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3IzejQ.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-140, -40, 880, 780);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Workerlogin WL = new Workerlogin();
        WL.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        String fName = WFName.getText();
        String lName = WLName.getText();
        String address = WAddress.getText();
        String email = WEmail.getText();
        String gender = "male", joinAs = "Tutor";
        if (jRadioButton_Male.isSelected()) {
            gender = "Male";
        }
        if (jRadioButton_Female.isSelected()) {
            gender = "Female";
        }
        String age = WAge.getText();

        if (jRadioButton_Tutor.isSelected()) {
            joinAs = "Tutor";
        }
        if (jRadioButton_Photographer.isSelected()) {
            joinAs = "Photographer";
        }
        String phone = WPhone.getText();
        String password = WPass.getText();

        String insertQuery = "Insert into worker_data(first_name,last_name,address,email,gender,Age,join_as,phone,password) Values('" + fName + "', '" + lName + "', '" + address + "', '" + email + "','" + gender + "', '" + age + "','" + joinAs + "','" + phone + "','" + password + "' )";
        try {
            stm = conn.obtainConnection().createStatement();
            stm.execute(insertQuery);
            JOptionPane.showMessageDialog(null, "Registration Succesfully! Please login..");
            
            Workerlogin WL = new Workerlogin();
            WL.setVisible(true);
            dispose();
            
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        // TODO add your handling code here:

    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(workReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(workReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(workReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(workReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new workReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField WAddress;
    private javax.swing.JTextField WAge;
    private javax.swing.JTextField WEmail;
    private javax.swing.JTextField WFName;
    private javax.swing.JTextField WLName;
    private javax.swing.JTextField WPass;
    private javax.swing.JTextField WPhone;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton_Female;
    private javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JRadioButton jRadioButton_Photographer;
    private javax.swing.JRadioButton jRadioButton_Tutor;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
